// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using boubackend.Data;

namespace boubackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("boubackend.Data.Vendors", b =>
                {
                    b.Property<int>("VendorsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FacebookPage");

                    b.Property<string>("FirstName");

                    b.Property<string>("InstagramPage");

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNum");

                    b.Property<string>("VendorBio");

                    b.Property<string>("VendorName");

                    b.Property<string>("WebAddress");

                    b.HasKey("VendorsId");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
